import type {
  DivisionInfo,
  StaffMember,
  ProjectInfo,
  ProjectStaff,
  PhDStudent,
  Equipment,
  ScientificOutput,
  IPIntelligence,
  Lab,
} from '../types';

export const mockDivisions: DivisionInfo[] = [
  {
    divCode: 'ARC', divName: 'Advanced Refractory Ceramics',
    divDescription: 'Research in refractory and ceramic materials for high-temperature industrial applications',
    divResearchAreas: 'Refractories, Ceramics, High-Temperature Materials, Castables',
    divHoD: 'Dr. A. K. Sharma', divHoDID: 'S001',
    divSanctionedstrength: 25, divCurrentStrength: 21, divStatus: 'Active',
  },
  {
    divCode: 'EEC', divName: 'Energy & Environment',
    divDescription: 'Energy materials research and environmental monitoring technologies',
    divResearchAreas: 'Fuel Cells, Energy Storage, Environmental Monitoring, Green Technologies',
    divHoD: 'Dr. R. Mishra', divHoDID: 'S012',
    divSanctionedstrength: 20, divCurrentStrength: 18, divStatus: 'Active',
  },
  {
    divCode: 'BMS', divName: 'Biomaterials & Sensors',
    divDescription: 'Development of biomedical materials and advanced sensor technologies',
    divResearchAreas: 'Biomaterials, Biosensors, Tissue Engineering, Medical Devices',
    divHoD: 'Dr. P. Singh', divHoDID: 'S025',
    divSanctionedstrength: 18, divCurrentStrength: 15, divStatus: 'Active',
  },
  {
    divCode: 'NST', divName: 'Nanomaterials & Surface Technology',
    divDescription: 'Nanomaterial synthesis, surface coatings, and thin film research',
    divResearchAreas: 'Nanomaterials, Surface Coatings, Thin Films, Carbon Nanomaterials',
    divHoD: 'Dr. S. Verma', divHoDID: 'S037',
    divSanctionedstrength: 22, divCurrentStrength: 19, divStatus: 'Active',
  },
  {
    divCode: 'CPS', divName: 'Corrosion Protection & Surface Engineering',
    divDescription: 'Corrosion science, protective coatings, and electrochemical engineering',
    divResearchAreas: 'Corrosion Science, Protective Coatings, Electrochemistry, Surface Engineering',
    divHoD: 'Dr. N. Patel', divHoDID: 'S040',
    divSanctionedstrength: 16, divCurrentStrength: 13, divStatus: 'Active',
  },
  {
    divCode: 'PMD', divName: 'Polymer & Mineral Processing',
    divDescription: 'Polymer composites and mineral beneficiation research',
    divResearchAreas: 'Polymer Composites, Mineral Processing, Beneficiation, Waste Utilization',
    divHoD: 'Dr. M. Jain', divHoDID: 'S045',
    divSanctionedstrength: 14, divCurrentStrength: 11, divStatus: 'Active',
  },
];

export const mockStaff: StaffMember[] = [
  {
    ID: 'S001', LabCode: 'AMPRI', EmployeeType: 'Permanent', Name: 'Dr. A. K. Sharma',
    Designation: 'Chief Scientist', Group: 'Scientific', Division: 'ARC',
    DoAPP: '2000-01-15', DOJ: '2000-01-15', DOB: '1968-03-20', Cat: 'I',
    AppointmentType: 'Direct', Level: '7', CoreArea: 'Refractories', Expertise: 'High-Temp Ceramics',
    Email: 'aksharma@ampri.res.in', Ext: '201', VidwanID: 'VID001', ReportingID: 'D001',
    HighestQualification: 'PhD', Gender: 'Male',
  },
  {
    ID: 'S002', LabCode: 'AMPRI', EmployeeType: 'Permanent', Name: 'Dr. Priya Mehta',
    Designation: 'Senior Scientist', Group: 'Scientific', Division: 'ARC',
    DoAPP: '2005-07-10', DOJ: '2005-07-10', DOB: '1975-11-05', Cat: 'I',
    AppointmentType: 'Direct', Level: '6', CoreArea: 'Ceramics', Expertise: 'Oxide Ceramics',
    Email: 'pmehta@ampri.res.in', Ext: '202', VidwanID: 'VID002', ReportingID: 'S001',
    HighestQualification: 'PhD', Gender: 'Female',
  },
  {
    ID: 'S003', LabCode: 'AMPRI', EmployeeType: 'Permanent', Name: 'Dr. Vikram Rao',
    Designation: 'Scientist', Group: 'Scientific', Division: 'ARC',
    DoAPP: '2015-04-01', DOJ: '2015-04-01', DOB: '1987-09-12', Cat: 'I',
    AppointmentType: 'Direct', Level: '5', CoreArea: 'Ceramics', Expertise: 'Structural Ceramics',
    Email: 'vrao@ampri.res.in', Ext: '203', VidwanID: 'VID003', ReportingID: 'S001',
    HighestQualification: 'PhD', Gender: 'Male',
  },
  {
    ID: 'S012', LabCode: 'AMPRI', EmployeeType: 'Permanent', Name: 'Dr. R. Mishra',
    Designation: 'Principal Scientist', Group: 'Scientific', Division: 'EEC',
    DoAPP: '2003-06-01', DOJ: '2003-06-01', DOB: '1970-09-12', Cat: 'I',
    AppointmentType: 'Direct', Level: '7', CoreArea: 'Energy Materials', Expertise: 'Solid Oxide Fuel Cells',
    Email: 'rmishra@ampri.res.in', Ext: '212', VidwanID: 'VID012', ReportingID: 'D001',
    HighestQualification: 'PhD', Gender: 'Male',
  },
  {
    ID: 'S013', LabCode: 'AMPRI', EmployeeType: 'Permanent', Name: 'Dr. Sunita Tiwari',
    Designation: 'Scientist', Group: 'Scientific', Division: 'EEC',
    DoAPP: '2012-09-01', DOJ: '2012-09-01', DOB: '1984-02-28', Cat: 'I',
    AppointmentType: 'Direct', Level: '5', CoreArea: 'Environment', Expertise: 'Air Quality Monitoring',
    Email: 'stiwari@ampri.res.in', Ext: '213', VidwanID: 'VID013', ReportingID: 'S012',
    HighestQualification: 'PhD', Gender: 'Female',
  },
  {
    ID: 'S014', LabCode: 'AMPRI', EmployeeType: 'Permanent', Name: 'Dr. Deepak Soni',
    Designation: 'Senior Scientist', Group: 'Scientific', Division: 'EEC',
    DoAPP: '2008-03-15', DOJ: '2008-03-15', DOB: '1978-06-22', Cat: 'I',
    AppointmentType: 'Direct', Level: '6', CoreArea: 'Energy Storage', Expertise: 'Battery Materials',
    Email: 'dsoni@ampri.res.in', Ext: '214', VidwanID: 'VID014', ReportingID: 'S012',
    HighestQualification: 'PhD', Gender: 'Male',
  },
  {
    ID: 'S025', LabCode: 'AMPRI', EmployeeType: 'Permanent', Name: 'Dr. P. Singh',
    Designation: 'Chief Scientist', Group: 'Scientific', Division: 'BMS',
    DoAPP: '1998-11-10', DOJ: '1998-11-10', DOB: '1965-06-30', Cat: 'I',
    AppointmentType: 'Direct', Level: '7', CoreArea: 'Biomaterials', Expertise: 'Tissue Engineering',
    Email: 'psingh@ampri.res.in', Ext: '225', VidwanID: 'VID025', ReportingID: 'D001',
    HighestQualification: 'PhD', Gender: 'Male',
  },
  {
    ID: 'S026', LabCode: 'AMPRI', EmployeeType: 'Permanent', Name: 'Dr. Ananya Desai',
    Designation: 'Scientist', Group: 'Scientific', Division: 'BMS',
    DoAPP: '2016-08-01', DOJ: '2016-08-01', DOB: '1988-12-10', Cat: 'I',
    AppointmentType: 'Direct', Level: '5', CoreArea: 'Biosensors', Expertise: 'Electrochemical Sensors',
    Email: 'adesai@ampri.res.in', Ext: '226', VidwanID: 'VID026', ReportingID: 'S025',
    HighestQualification: 'PhD', Gender: 'Female',
  },
  {
    ID: 'S037', LabCode: 'AMPRI', EmployeeType: 'Permanent', Name: 'Dr. S. Verma',
    Designation: 'Principal Scientist', Group: 'Scientific', Division: 'NST',
    DoAPP: '2006-04-15', DOJ: '2006-04-15', DOB: '1973-01-18', Cat: 'I',
    AppointmentType: 'Direct', Level: '7', CoreArea: 'Nanomaterials', Expertise: 'Carbon Nanomaterials',
    Email: 'sverma@ampri.res.in', Ext: '237', VidwanID: 'VID037', ReportingID: 'D001',
    HighestQualification: 'PhD', Gender: 'Female',
  },
  {
    ID: 'S040', LabCode: 'AMPRI', EmployeeType: 'Permanent', Name: 'Dr. N. Patel',
    Designation: 'Chief Scientist', Group: 'Scientific', Division: 'CPS',
    DoAPP: '2001-07-01', DOJ: '2001-07-01', DOB: '1969-04-15', Cat: 'I',
    AppointmentType: 'Direct', Level: '7', CoreArea: 'Corrosion Science', Expertise: 'Protective Coatings',
    Email: 'npatel@ampri.res.in', Ext: '240', VidwanID: 'VID040', ReportingID: 'D001',
    HighestQualification: 'PhD', Gender: 'Male',
  },
  {
    ID: 'S045', LabCode: 'AMPRI', EmployeeType: 'Permanent', Name: 'Dr. M. Jain',
    Designation: 'Principal Scientist', Group: 'Scientific', Division: 'PMD',
    DoAPP: '2004-09-01', DOJ: '2004-09-01', DOB: '1972-11-25', Cat: 'I',
    AppointmentType: 'Direct', Level: '7', CoreArea: 'Polymer Composites', Expertise: 'Fiber Reinforced Polymers',
    Email: 'mjain@ampri.res.in', Ext: '245', VidwanID: 'VID045', ReportingID: 'D001',
    HighestQualification: 'PhD', Gender: 'Male',
  },
  {
    ID: 'T001', LabCode: 'AMPRI', EmployeeType: 'Permanent', Name: 'Rajesh Kumar',
    Designation: 'Technical Officer', Group: 'Technical', Division: 'ARC',
    DoAPP: '2010-03-01', DOJ: '2010-03-01', DOB: '1982-07-15', Cat: 'II',
    AppointmentType: 'Direct', Level: '4', CoreArea: 'Lab Operations', Expertise: 'XRD Analysis',
    Email: 'rkumar@ampri.res.in', Ext: '301', VidwanID: '', ReportingID: 'S001',
    HighestQualification: 'M.Sc.', Gender: 'Male',
  },
  {
    ID: 'T002', LabCode: 'AMPRI', EmployeeType: 'Permanent', Name: 'Anil Gupta',
    Designation: 'Technical Officer', Group: 'Technical', Division: 'NST',
    DoAPP: '2008-08-20', DOJ: '2008-08-20', DOB: '1980-04-10', Cat: 'II',
    AppointmentType: 'Direct', Level: '4', CoreArea: 'Thin Films', Expertise: 'PVD Coatings',
    Email: 'agupta@ampri.res.in', Ext: '302', VidwanID: '', ReportingID: 'S037',
    HighestQualification: 'B.Tech', Gender: 'Male',
  },
  {
    ID: 'T003', LabCode: 'AMPRI', EmployeeType: 'Permanent', Name: 'Suman Devi',
    Designation: 'Technical Officer', Group: 'Technical', Division: 'EEC',
    DoAPP: '2011-06-15', DOJ: '2011-06-15', DOB: '1983-10-02', Cat: 'II',
    AppointmentType: 'Direct', Level: '4', CoreArea: 'Thermal Analysis', Expertise: 'TGA/DSC Operations',
    Email: 'sdevi@ampri.res.in', Ext: '303', VidwanID: '', ReportingID: 'S012',
    HighestQualification: 'M.Tech', Gender: 'Female',
  },
  {
    ID: 'T004', LabCode: 'AMPRI', EmployeeType: 'Permanent', Name: 'Ravi Pandey',
    Designation: 'Technical Officer', Group: 'Technical', Division: 'CPS',
    DoAPP: '2013-01-10', DOJ: '2013-01-10', DOB: '1985-05-20', Cat: 'II',
    AppointmentType: 'Direct', Level: '4', CoreArea: 'Electrochemistry', Expertise: 'Corrosion Testing',
    Email: 'rpandey@ampri.res.in', Ext: '304', VidwanID: '', ReportingID: 'S040',
    HighestQualification: 'M.Sc.', Gender: 'Male',
  },
  {
    ID: 'H001', LabCode: 'AMPRI', EmployeeType: 'Permanent', Name: 'Kavita Sharma',
    Designation: 'Administrative Officer', Group: 'Admin', Division: 'ARC',
    DoAPP: '2007-05-01', DOJ: '2007-05-01', DOB: '1979-08-22', Cat: 'III',
    AppointmentType: 'Direct', Level: '3', CoreArea: 'HR', Expertise: 'Personnel Management',
    Email: 'hr@ampri.res.in', Ext: '101', VidwanID: '', ReportingID: 'D001',
    HighestQualification: 'MBA', Gender: 'Female',
  },
  {
    ID: 'H002', LabCode: 'AMPRI', EmployeeType: 'Permanent', Name: 'Manoj Thakur',
    Designation: 'Finance Officer', Group: 'Admin', Division: 'ARC',
    DoAPP: '2009-02-01', DOJ: '2009-02-01', DOB: '1977-03-14', Cat: 'III',
    AppointmentType: 'Direct', Level: '3', CoreArea: 'Finance', Expertise: 'Budget & Accounts',
    Email: 'finance@ampri.res.in', Ext: '102', VidwanID: '', ReportingID: 'D001',
    HighestQualification: 'CA', Gender: 'Male',
  },
];

export const mockProjects: ProjectInfo[] = [
  {
    ProjectID: 'P001', ProjectNo: 'OLP-2023-01', ProjectName: 'Development of High-Temperature Refractory Linings',
    FundType: 'In-House', SponsorerType: 'CSIR', SponsorerName: 'CSIR', ProjectCategory: 'R&D',
    ProjectStatus: 'Active', StartDate: '2023-04-01', CompletioDate: '2026-03-31',
    SanctionedCost: '5000000', UtilizedAmount: '2100000',
    PrincipalInvestigator: 'Dr. A. K. Sharma', DivisionCode: 'ARC',
    Extension: '', ApprovalAuthority: 'CSIR-HQ',
  },
  {
    ProjectID: 'P002', ProjectNo: 'EXP-2022-05', ProjectName: 'SOFC Electrolyte Optimization for Intermediate Temperatures',
    FundType: 'Extramural', SponsorerType: 'Government', SponsorerName: 'DST', ProjectCategory: 'R&D',
    ProjectStatus: 'Active', StartDate: '2022-01-01', CompletioDate: '2025-12-31',
    SanctionedCost: '8500000', UtilizedAmount: '6200000',
    PrincipalInvestigator: 'Dr. R. Mishra', DivisionCode: 'EEC',
    Extension: 'Yes', ApprovalAuthority: 'DST',
  },
  {
    ProjectID: 'P003', ProjectNo: 'CNS-2024-02', ProjectName: 'Electrochemical Biosensor for Heavy Metal Detection in Water',
    FundType: 'Extramural', SponsorerType: 'Industry', SponsorerName: 'TCS', ProjectCategory: 'Consultancy',
    ProjectStatus: 'Active', StartDate: '2024-01-15', CompletioDate: '2025-06-30',
    SanctionedCost: '3200000', UtilizedAmount: '1800000',
    PrincipalInvestigator: 'Dr. P. Singh', DivisionCode: 'BMS',
    Extension: '', ApprovalAuthority: 'CSIR-AMPRI Director',
  },
  {
    ProjectID: 'P004', ProjectNo: 'NNO-2021-08', ProjectName: 'Carbon Nanotube Reinforced SiC Composites for Aerospace',
    FundType: 'Extramural', SponsorerType: 'Government', SponsorerName: 'DRDO', ProjectCategory: 'R&D',
    ProjectStatus: 'Completed', StartDate: '2021-07-01', CompletioDate: '2024-06-30',
    SanctionedCost: '12000000', UtilizedAmount: '11800000',
    PrincipalInvestigator: 'Dr. S. Verma', DivisionCode: 'NST',
    Extension: '', ApprovalAuthority: 'DRDO',
  },
  {
    ProjectID: 'P005', ProjectNo: 'OLP-2024-03', ProjectName: 'Eco-Friendly Binder Systems for Advanced Ceramics',
    FundType: 'In-House', SponsorerType: 'CSIR', SponsorerName: 'CSIR', ProjectCategory: 'R&D',
    ProjectStatus: 'Active', StartDate: '2024-04-01', CompletioDate: '2027-03-31',
    SanctionedCost: '4500000', UtilizedAmount: '800000',
    PrincipalInvestigator: 'Dr. Priya Mehta', DivisionCode: 'ARC',
    Extension: '', ApprovalAuthority: 'CSIR-HQ',
  },
  {
    ProjectID: 'P006', ProjectNo: 'EXP-2024-07', ProjectName: 'Anti-Corrosion Coatings for Marine Steel Structures',
    FundType: 'Extramural', SponsorerType: 'Government', SponsorerName: 'Indian Navy (DRDO)', ProjectCategory: 'R&D',
    ProjectStatus: 'Active', StartDate: '2024-06-01', CompletioDate: '2027-05-31',
    SanctionedCost: '9500000', UtilizedAmount: '1200000',
    PrincipalInvestigator: 'Dr. N. Patel', DivisionCode: 'CPS',
    Extension: '', ApprovalAuthority: 'DRDO',
  },
  {
    ProjectID: 'P007', ProjectNo: 'EXP-2023-11', ProjectName: 'Lithium-Ion Battery Cathode Materials from Indian Minerals',
    FundType: 'Extramural', SponsorerType: 'Government', SponsorerName: 'MNRE', ProjectCategory: 'R&D',
    ProjectStatus: 'Active', StartDate: '2023-10-01', CompletioDate: '2026-09-30',
    SanctionedCost: '7200000', UtilizedAmount: '3400000',
    PrincipalInvestigator: 'Dr. Deepak Soni', DivisionCode: 'EEC',
    Extension: '', ApprovalAuthority: 'MNRE',
  },
  {
    ProjectID: 'P008', ProjectNo: 'CNS-2025-01', ProjectName: 'Fly Ash Utilization in Polymer Composites',
    FundType: 'Extramural', SponsorerType: 'Industry', SponsorerName: 'NTPC Ltd', ProjectCategory: 'Consultancy',
    ProjectStatus: 'Active', StartDate: '2025-01-15', CompletioDate: '2026-07-14',
    SanctionedCost: '2800000', UtilizedAmount: '400000',
    PrincipalInvestigator: 'Dr. M. Jain', DivisionCode: 'PMD',
    Extension: '', ApprovalAuthority: 'CSIR-AMPRI Director',
  },
];

export const mockProjectStaff: ProjectStaff[] = [
  {
    id: 'PS001', ProjectNo: 'OLP-2023-01', StaffName: 'Ramesh Yadav',
    Designation: 'Project Assistant', RecruitmentCycle: '2023',
    DateOfJoining: '2023-06-01', DateOfProjectDuration: '2026-03-31', PIName: 'Dr. A. K. Sharma', DivisionCode: 'ARC',
  },
  {
    id: 'PS002', ProjectNo: 'EXP-2022-05', StaffName: 'Meena Patel',
    Designation: 'Junior Research Fellow', RecruitmentCycle: '2022',
    DateOfJoining: '2022-03-01', DateOfProjectDuration: '2025-02-28', PIName: 'Dr. R. Mishra', DivisionCode: 'EEC',
  },
  {
    id: 'PS003', ProjectNo: 'CNS-2024-02', StaffName: 'Vivek Joshi',
    Designation: 'Project Associate', RecruitmentCycle: '2024',
    DateOfJoining: '2024-02-01', DateOfProjectDuration: '2025-06-30', PIName: 'Dr. P. Singh', DivisionCode: 'BMS',
  },
  {
    id: 'PS004', ProjectNo: 'OLP-2024-03', StaffName: 'Anjali Dixit',
    Designation: 'Senior Research Fellow', RecruitmentCycle: '2024',
    DateOfJoining: '2024-05-01', DateOfProjectDuration: '2027-03-31', PIName: 'Dr. Priya Mehta', DivisionCode: 'ARC',
  },
  {
    id: 'PS005', ProjectNo: 'EXP-2024-07', StaffName: 'Rohit Chauhan',
    Designation: 'Junior Research Fellow', RecruitmentCycle: '2024',
    DateOfJoining: '2024-08-01', DateOfProjectDuration: '2027-05-31', PIName: 'Dr. N. Patel', DivisionCode: 'CPS',
  },
  {
    id: 'PS006', ProjectNo: 'EXP-2023-11', StaffName: 'Neha Agrawal',
    Designation: 'Senior Research Fellow', RecruitmentCycle: '2023',
    DateOfJoining: '2023-12-01', DateOfProjectDuration: '2026-09-30', PIName: 'Dr. Deepak Soni', DivisionCode: 'EEC',
  },
];

export const mockPhDStudents: PhDStudent[] = [
  {
    EnrollmentNo: 'PHD2019001', StudentName: 'Arjun Nair', Specialization: 'Refractory Ceramics',
    SupervisorName: 'Dr. A. K. Sharma', CoSupervisorName: 'Dr. Priya Mehta',
    FellowshipDetails: 'SRF-CSIR', CurrentStatus: 'Thesis Submitted',
    ThesisTitle: 'Novel Castable Refractories for Steelmaking', ProjectNo: 'OLP-2023-01', DivisionCode: 'ARC',
  },
  {
    EnrollmentNo: 'PHD2021003', StudentName: 'Divya Kapoor', Specialization: 'Energy Materials',
    SupervisorName: 'Dr. R. Mishra', CoSupervisorName: '',
    FellowshipDetails: 'JRF-CSIR', CurrentStatus: 'Ongoing',
    ThesisTitle: 'SOFC Cathode Materials for Intermediate Temperature Operation', ProjectNo: 'EXP-2022-05', DivisionCode: 'EEC',
  },
  {
    EnrollmentNo: 'PHD2022005', StudentName: 'Karan Bose', Specialization: 'Nanomaterials',
    SupervisorName: 'Dr. S. Verma', CoSupervisorName: '',
    FellowshipDetails: 'SRF-UGC', CurrentStatus: 'Ongoing',
    ThesisTitle: 'Functionalized Carbon Nanotubes for Composite Reinforcement', ProjectNo: 'NNO-2021-08', DivisionCode: 'NST',
  },
  {
    EnrollmentNo: 'PHD2023007', StudentName: 'Pooja Sharma', Specialization: 'Ceramics',
    SupervisorName: 'Dr. Priya Mehta', CoSupervisorName: 'Dr. A. K. Sharma',
    FellowshipDetails: 'JRF-DST', CurrentStatus: 'Coursework',
    ThesisTitle: 'Alumina-Zirconia Ceramics for Biomedical Applications', ProjectNo: '', DivisionCode: 'ARC',
  },
  {
    EnrollmentNo: 'PHD2020002', StudentName: 'Manish Tripathi', Specialization: 'Biomaterials',
    SupervisorName: 'Dr. P. Singh', CoSupervisorName: '',
    FellowshipDetails: 'SRF-ICMR', CurrentStatus: 'Ongoing',
    ThesisTitle: 'Hydroxyapatite Scaffolds for Bone Tissue Engineering', ProjectNo: 'CNS-2024-02', DivisionCode: 'BMS',
  },
  {
    EnrollmentNo: 'PHD2022009', StudentName: 'Shreya Kulkarni', Specialization: 'Corrosion Science',
    SupervisorName: 'Dr. N. Patel', CoSupervisorName: '',
    FellowshipDetails: 'JRF-CSIR', CurrentStatus: 'Ongoing',
    ThesisTitle: 'Graphene-Modified Epoxy Coatings for Marine Corrosion Protection', ProjectNo: 'EXP-2024-07', DivisionCode: 'CPS',
  },
  {
    EnrollmentNo: 'PHD2023011', StudentName: 'Amit Tiwari', Specialization: 'Battery Materials',
    SupervisorName: 'Dr. Deepak Soni', CoSupervisorName: 'Dr. R. Mishra',
    FellowshipDetails: 'JRF-MNRE', CurrentStatus: 'Coursework',
    ThesisTitle: 'Manganese-Rich Cathodes for Next-Gen Li-Ion Batteries', ProjectNo: 'EXP-2023-11', DivisionCode: 'EEC',
  },
  {
    EnrollmentNo: 'PHD2024001', StudentName: 'Nidhi Saxena', Specialization: 'Polymer Composites',
    SupervisorName: 'Dr. M. Jain', CoSupervisorName: '',
    FellowshipDetails: 'JRF-CSIR', CurrentStatus: 'Coursework',
    ThesisTitle: 'Fly Ash Filled Polymer Composites for Structural Applications', ProjectNo: 'CNS-2025-01', DivisionCode: 'PMD',
  },
];

export const mockLabs: Lab[] = [
  { id: 'LAB-001', lab_code: 'LAB-ARC-01', lab_name: 'X-Ray & Thermal Analysis Lab',   div_code: 'ARC' },
  { id: 'LAB-002', lab_code: 'LAB-NST-01', lab_name: 'Electron Microscopy Suite',       div_code: 'NST' },
  { id: 'LAB-003', lab_code: 'LAB-EEC-01', lab_name: 'Electrochemistry & Optical Lab',  div_code: 'EEC' },
  { id: 'LAB-004', lab_code: 'LAB-BMS-01', lab_name: 'Biomaterials & Sensors Lab',      div_code: 'BMS' },
  { id: 'LAB-005', lab_code: 'LAB-CPS-01', lab_name: 'Corrosion Testing Lab',           div_code: 'CPS' },
  { id: 'LAB-006', lab_code: 'LAB-PMD-01', lab_name: 'Powder Processing & Polymer Lab', div_code: 'PMD' },
];

export const mockEquipment: Equipment[] = [
  {
    UInsID: 'E001', instrument_code: 'XRD-001',
    Name: 'X-Ray Diffractometer (XRD)', serial_number: 'RL-XRD-2019-0042',
    manufacturer: 'Rigaku', year_of_manufacture: 2019,
    EndUse: 'Phase Analysis', lab_id: 'LAB-001', Division: 'ARC',
    IndenterName: 'Dr. A. K. Sharma', OperatorName: 'Rajesh Kumar',
    Location: 'Lab-A101', amc_end_date: '2024-12-31',
    WorkingStatus: 'Working', Movable: 'No',
    purchase_cost: 4200000, procurement_date: '2019-06-15',
    RequirementInstallation: 'Completed', Justification: 'Phase identification of ceramics',
    Remark: 'AMC expired — renewal pending',
  },
  {
    UInsID: 'E002', instrument_code: 'SEM-001',
    Name: 'Scanning Electron Microscope (SEM)', serial_number: 'ZEISS-EVO-2020-0117',
    manufacturer: 'ZEISS', year_of_manufacture: 2020,
    EndUse: 'Microstructure Analysis', lab_id: 'LAB-002', Division: 'NST',
    IndenterName: 'Dr. S. Mishra', OperatorName: 'Shri D. K. Pandey',
    Location: 'Lab-D301', amc_end_date: '2026-08-31',
    WorkingStatus: 'Working', Movable: 'No',
    purchase_cost: 12500000, procurement_date: '2020-03-10',
    RequirementInstallation: 'Completed', Justification: 'Microstructural characterization across divisions',
    Remark: '',
  },
  {
    UInsID: 'E003', instrument_code: 'TGA-001',
    Name: 'Thermogravimetric Analyzer (TGA)', serial_number: 'TA-Q500-2021-0033',
    manufacturer: 'TA Instruments', year_of_manufacture: 2021,
    EndUse: 'Thermal Analysis', lab_id: 'LAB-001', Division: 'EEC',
    IndenterName: 'Dr. P. Nair', OperatorName: 'Smt. R. Bhatt',
    Location: 'Lab-B201', amc_end_date: '2026-03-31',
    WorkingStatus: 'Working', Movable: 'Yes',
    purchase_cost: 1800000, procurement_date: '2021-09-01',
    RequirementInstallation: 'Completed', Justification: 'Thermal stability testing for energy materials',
    Remark: '',
  },
  {
    UInsID: 'E004', instrument_code: 'AFM-001',
    Name: 'Atomic Force Microscope (AFM)', serial_number: 'BRK-DIM-2022-0009',
    manufacturer: 'Bruker', year_of_manufacture: 2022,
    EndUse: 'Surface Imaging', lab_id: 'LAB-002', Division: 'NST',
    IndenterName: 'Dr. A. Patel', OperatorName: 'Shri D. K. Pandey',
    Location: 'Lab-D302', amc_end_date: '2025-04-10',
    WorkingStatus: 'Working', Movable: 'No',
    purchase_cost: 7500000, procurement_date: '2022-02-20',
    RequirementInstallation: 'Completed', Justification: 'Nanoscale surface characterization for thin films',
    Remark: 'AMC expires soon — contact Bruker India',
  },
  {
    UInsID: 'E005', instrument_code: 'PGSTAT-001',
    Name: 'Potentiostat/Galvanostat', serial_number: 'MAU-PGSTAT302N-2020-0055',
    manufacturer: 'Metrohm Autolab', year_of_manufacture: 2020,
    EndUse: 'Electrochemical Testing', lab_id: 'LAB-003', Division: 'EEC',
    IndenterName: 'Dr. V. S. Rathore', OperatorName: 'Shri A. Soni',
    Location: 'Lab-C201', amc_end_date: '2026-12-31',
    WorkingStatus: 'Working', Movable: 'Yes',
    purchase_cost: 950000, procurement_date: '2020-11-05',
    RequirementInstallation: 'Completed', Justification: 'Corrosion and energy storage testing',
    Remark: 'Shared between CPS and EEC divisions',
  },
  {
    UInsID: 'E006', instrument_code: 'HTF-001',
    Name: 'High-Temperature Box Furnace (1800°C)', serial_number: 'NAB-LHT-2018-0077',
    manufacturer: 'Nabertherm', year_of_manufacture: 2018,
    EndUse: 'Sintering', lab_id: 'LAB-001', Division: 'ARC',
    IndenterName: 'Dr. A. K. Sharma', OperatorName: 'Shri R. Yadav',
    Location: 'Lab-A103', amc_end_date: '2023-06-30',
    WorkingStatus: 'Not Working', Movable: 'No',
    purchase_cost: 2200000, procurement_date: '2018-12-01',
    RequirementInstallation: 'Completed', Justification: 'Ceramic sintering operations',
    Remark: 'Heating element failure — repair order placed. AMC lapsed.',
  },
  {
    UInsID: 'E007', instrument_code: 'UTM-001',
    Name: 'Universal Testing Machine (UTM)', serial_number: 'INS-5982-2021-0014',
    manufacturer: 'Instron', year_of_manufacture: 2021,
    EndUse: 'Mechanical Testing', lab_id: 'LAB-005', Division: 'ARC',
    IndenterName: 'Dr. M. K. Gupta', OperatorName: 'Shri R. Yadav',
    Location: 'Lab-E101', amc_end_date: '2026-06-30',
    WorkingStatus: 'Working', Movable: 'No',
    purchase_cost: 3100000, procurement_date: '2021-07-18',
    RequirementInstallation: 'Completed', Justification: 'Tensile and compressive strength testing',
    Remark: '',
  },
  {
    UInsID: 'E008', instrument_code: 'DSC-001',
    Name: 'Differential Scanning Calorimeter (DSC)', serial_number: 'MTT-DSC3-2022-0021',
    manufacturer: 'Mettler Toledo', year_of_manufacture: 2022,
    EndUse: 'Thermal Analysis', lab_id: 'LAB-006', Division: 'EEC',
    IndenterName: 'Dr. K. Joshi', OperatorName: 'Smt. R. Bhatt',
    Location: 'Lab-F101', amc_end_date: '2026-09-30',
    WorkingStatus: 'Working', Movable: 'Yes',
    purchase_cost: 1650000, procurement_date: '2022-06-10',
    RequirementInstallation: 'Completed', Justification: 'Glass transition and melting analysis of polymers',
    Remark: '',
  },
  {
    UInsID: 'E009', instrument_code: 'TEM-001',
    Name: 'Transmission Electron Microscope (TEM)', serial_number: 'JEL-JEM2100-2019-0006',
    manufacturer: 'JEOL', year_of_manufacture: 2019,
    EndUse: 'Nanoscale Imaging', lab_id: 'LAB-002', Division: 'NST',
    IndenterName: 'Dr. S. Mishra', OperatorName: 'Shri D. K. Pandey',
    Location: 'Lab-D303', amc_end_date: '2026-01-31',
    WorkingStatus: 'Working', Movable: 'No',
    purchase_cost: 18000000, procurement_date: '2019-10-25',
    RequirementInstallation: 'Completed', Justification: 'High-resolution imaging of nanomaterials',
    Remark: 'Shared facility with BMS division',
  },
  {
    UInsID: 'E010', instrument_code: 'SSC-001',
    Name: 'Salt Spray Chamber', serial_number: 'SCH-SSC-2020-0038',
    manufacturer: 'Schutz Messtechnik', year_of_manufacture: 2020,
    EndUse: 'Corrosion Testing', lab_id: 'LAB-005', Division: 'CPS',
    IndenterName: 'Dr. V. S. Rathore', OperatorName: 'Shri A. Soni',
    Location: 'Lab-E102', amc_end_date: '2026-11-30',
    WorkingStatus: 'Working', Movable: 'No',
    purchase_cost: 480000, procurement_date: '2020-08-12',
    RequirementInstallation: 'Completed', Justification: 'Accelerated corrosion testing per ASTM B117',
    Remark: '',
  },
];

export const mockScientificOutputs: ScientificOutput[] = [
  {
    id: 'SO001', title: 'Advanced castable refractories with nano-additions for steel ladle applications',
    authors: ['Dr. A. K. Sharma', 'Dr. Priya Mehta', 'Arjun Nair'],
    journal: 'Journal of the European Ceramic Society', year: 2024,
    doi: '10.1016/j.jeurceramsoc.2024.01.001', impactFactor: 5.8, citationCount: 12,
    divisionCode: 'ARC',
  },
  {
    id: 'SO002', title: 'Proton-conducting ceramics for intermediate-temperature SOFCs',
    authors: ['Dr. R. Mishra', 'Divya Kapoor'],
    journal: 'Journal of Power Sources', year: 2023,
    doi: '10.1016/j.jpowsour.2023.05.012', impactFactor: 9.2, citationCount: 28,
    divisionCode: 'EEC',
  },
  {
    id: 'SO003', title: 'Carbon nanotube reinforced SiC composites for high-temperature aerospace applications',
    authors: ['Dr. S. Verma', 'Karan Bose'],
    journal: 'Composites Part B: Engineering', year: 2024,
    doi: '10.1016/j.compositesb.2024.03.005', impactFactor: 13.1, citationCount: 7,
    divisionCode: 'NST',
  },
  {
    id: 'SO004', title: 'Hydroxyapatite-chitosan scaffolds for bone regeneration',
    authors: ['Dr. P. Singh', 'Manish Tripathi'],
    journal: 'Biomaterials Science', year: 2023,
    doi: '10.1039/d3bm00234g', impactFactor: 7.5, citationCount: 19,
    divisionCode: 'BMS',
  },
  {
    id: 'SO005', title: 'Graphene-oxide modified epoxy coatings for marine corrosion protection',
    authors: ['Dr. N. Patel', 'Shreya Kulkarni'],
    journal: 'Corrosion Science', year: 2024,
    doi: '10.1016/j.corsci.2024.02.018', impactFactor: 7.4, citationCount: 5,
    divisionCode: 'CPS',
  },
  {
    id: 'SO006', title: 'Manganese-rich cathode materials from Indian mineral resources',
    authors: ['Dr. Deepak Soni', 'Amit Tiwari', 'Dr. R. Mishra'],
    journal: 'ACS Applied Energy Materials', year: 2025,
    doi: '10.1021/acsaem.2025.00112', impactFactor: 6.4, citationCount: 2,
    divisionCode: 'EEC',
  },
  {
    id: 'SO007', title: 'Fly ash-reinforced polypropylene composites: mechanical and thermal behavior',
    authors: ['Dr. M. Jain', 'Nidhi Saxena'],
    journal: 'Polymer Composites', year: 2024,
    doi: '10.1002/pc.28150', impactFactor: 4.8, citationCount: 3,
    divisionCode: 'PMD',
  },
  {
    id: 'SO008', title: 'Electrochemical biosensor for trace Pb(II) detection using ZnO nanostructures',
    authors: ['Dr. P. Singh', 'Dr. Ananya Desai', 'Manish Tripathi'],
    journal: 'Sensors and Actuators B: Chemical', year: 2024,
    doi: '10.1016/j.snb.2024.06.045', impactFactor: 8.4, citationCount: 9,
    divisionCode: 'BMS',
  },
];

export const mockIPIntelligence: IPIntelligence[] = [
  {
    id: 'IP001', title: 'Nano-Al2O3 Modified Castable Refractory Composition',
    type: 'Patent', status: 'Granted', filingDate: '2022-08-15',
    grantDate: '2024-03-20', inventors: ['Dr. A. K. Sharma', 'Dr. Priya Mehta'],
    divisionCode: 'ARC',
  },
  {
    id: 'IP002', title: 'Electrochemical Biosensor for Pb(II) Detection in Drinking Water',
    type: 'Patent', status: 'Published', filingDate: '2023-11-01',
    inventors: ['Dr. P. Singh', 'Manish Tripathi'], divisionCode: 'BMS',
  },
  {
    id: 'IP003', title: 'Self-Healing Epoxy Coating Composition for Marine Applications',
    type: 'Patent', status: 'Filed', filingDate: '2024-09-15',
    inventors: ['Dr. N. Patel', 'Shreya Kulkarni'], divisionCode: 'CPS',
  },
  {
    id: 'IP004', title: 'Process for Extraction of Lithium from Low-Grade Indian Mica',
    type: 'Patent', status: 'Published', filingDate: '2024-02-10',
    inventors: ['Dr. Deepak Soni', 'Dr. R. Mishra'], divisionCode: 'EEC',
  },
  {
    id: 'IP005', title: 'CNT-Reinforced Ceramic Matrix Composite and Method of Manufacture',
    type: 'Patent', status: 'Granted', filingDate: '2021-05-20',
    grantDate: '2023-11-08', inventors: ['Dr. S. Verma', 'Karan Bose'],
    divisionCode: 'NST',
  },
];
