// scripts/generate-seed.ts
//
// Throwaway script — emits the SQL block that is appended to
// supabase/seed.sql. Run once with: npx tsx scripts/generate-seed.ts > /tmp/seed-block.sql
// Review the output, then paste under the "DEMO SEED (generated)" divider in
// supabase/seed.sql. Delete this script after merge (or keep + add an npm
// script — see Task 4).

import {
  mockCommittees, mockCommitteeMembers, mockMeetings, mockAgendaItems,
  mockActionItems, mockMeetingDocuments,
  mockTickets, mockTicketResponses, mockTicketEvents,
  mockVacancyAdvertisements, mockVacancyPosts,
} from '../src/utils/mockData';

// --- SQL value serialization ---------------------------------------------

function sqlVal(v: unknown): string {
  if (v === null || v === undefined || v === '') return 'NULL';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'boolean') return v ? 'TRUE' : 'FALSE';
  if (Array.isArray(v)) {
    // PostgreSQL ARRAY[...] literal of strings/numbers.
    const items = v.map(x => (typeof x === 'number' ? String(x) : `'${String(x).replace(/'/g, "''")}'`));
    return `ARRAY[${items.join(', ')}]`;
  }
  if (typeof v === 'object') {
    // JSONB column — emit as quoted JSON string.
    return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
  }
  return `'${String(v).replace(/'/g, "''")}'`;
}

function insertBlock<T extends Record<string, unknown>>(
  table: string,
  columns: string[],
  rows: T[],
  options: { quoteIdent?: boolean; onConflict?: string } = {}
): string {
  if (rows.length === 0) return `-- ${table}: no rows\n`;
  const quoted = options.quoteIdent ? columns.map(c => `"${c}"`) : columns;
  const values = rows.map(r => `    (${columns.map(c => sqlVal(r[c])).join(', ')})`).join(',\n');
  const conflict = options.onConflict ? `\n${options.onConflict}` : '';
  return `\n-- ${table}\nINSERT INTO public.${table}\n    (${quoted.join(', ')})\nVALUES\n${values}${conflict};\n`;
}

// --- Emit each block in dependency order ---------------------------------

const out: string[] = [];

out.push('-- ============================================================');
out.push('-- DEMO SEED (generated by scripts/generate-seed.ts)');
out.push('-- Generated on first run; review then commit. Do not hand-edit.');
out.push('-- ============================================================');

out.push(insertBlock('committees',
  ['id', 'name', 'committee_type', 'mandate', 'chairperson_id', 'secretary_id', 'status', 'formed_date', 'created_at'],
  mockCommittees,
  { onConflict: 'ON CONFLICT (id) DO NOTHING' }
));

out.push(insertBlock('committee_members',
  ['id', 'committee_id', 'staff_id', 'role'],
  mockCommitteeMembers,
  { onConflict: 'ON CONFLICT (id) DO NOTHING' }
));

out.push(insertBlock('meetings',
  ['id', 'committee_id', 'meeting_date', 'venue', 'title', 'summary', 'status', 'created_at'],
  mockMeetings,
  { onConflict: 'ON CONFLICT (id) DO NOTHING' }
));

out.push(insertBlock('agenda_items',
  ['id', 'meeting_id', 'sequence', 'title', 'description', 'decision'],
  mockAgendaItems,
  { onConflict: 'ON CONFLICT (id) DO NOTHING' }
));

out.push(insertBlock('action_items',
  ['id', 'meeting_id', 'description', 'owner_id', 'due_date', 'status', 'created_at'],
  mockActionItems,
  { onConflict: 'ON CONFLICT (id) DO NOTHING' }
));

out.push(insertBlock('meeting_documents',
  ['id', 'meeting_id', 'file_name', 'file_path', 'uploaded_by', 'uploaded_at'],
  mockMeetingDocuments,
  { onConflict: 'ON CONFLICT (id) DO NOTHING' }
));

out.push(insertBlock('tickets',
  ['id', 'token', 'subject', 'category', 'urgency', 'description', 'submitted_by', 'assigned_to', 'status', 'created_at', 'updated_at', 'resolved_at'],
  mockTickets,
  { onConflict: 'ON CONFLICT (id) DO NOTHING' }
));

out.push(insertBlock('ticket_responses',
  ['id', 'ticket_id', 'author_id', 'message', 'created_at'],
  mockTicketResponses,
  { onConflict: 'ON CONFLICT (id) DO NOTHING' }
));

out.push(insertBlock('ticket_events',
  ['id', 'ticket_id', 'event_type', 'actor_id', 'details', 'created_at'],
  mockTicketEvents,
  { onConflict: 'ON CONFLICT (id) DO NOTHING' }
));

// Recruitment uses camelCase columns — verify against init.sql before running.
out.push(insertBlock('vacancy_advertisements',
  ['id', 'title', 'description', 'designation', 'division', 'numberOfPositions', 'qualifications', 'salary', 'applicationDeadline', 'createdAt', 'status'],
  mockVacancyAdvertisements,
  { quoteIdent: true, onConflict: 'ON CONFLICT (id) DO NOTHING' }
));

out.push(insertBlock('vacancy_posts',
  ['id', 'vacancyId', 'candidateName', 'email', 'phoneNumber', 'qualifications', 'experience', 'applicationDate', 'status', 'notes'],
  mockVacancyPosts,
  { quoteIdent: true, onConflict: 'ON CONFLICT (id) DO NOTHING' }
));

console.log(out.join('\n'));
